dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.5.0
  - smartcontractkit/chainlink@1.1.0

compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'
      - '@chainlink=smartcontractkit/chainlink@1.1.0'

dotenv: .env

wallets:
  dev_account_1: 
    address: ${D1_ADDRESS}
    private_key: ${D1_PRIVATE_KEY}

networks:

  development:
    local: True
    verify: False
    vrf_key_hash : '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    vrf_fee : 100000000000000000

  mainnet-fork-dev:
    local: 'fork'
    verify: True

  rinkeby:
    local: False
    verify: True
    link_token : '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
    vrf_coordinator : '0xb3dCcb4Cf7a26f6cf6B120Cf5A73875B7BBc655B'
    vrf_key_hash : '0x2ed0feb3e7fd2022120aa84fab1945545a9f2ffc9076fd6156fa96eaff4c1311'
    vrf_fee : 100000000000000000
    